stages:
  - test
  - deploy

deb_package_check:
  image: debian:jessie
  script: tests/deb_package_check.sh
  before_script:
    - apt-get update -q >/dev/null
    - apt-get install -q -y fakeroot lintian >/dev/null
  stage: test
  tags:
    - deb_check
  only:
    - tags
    - master
    - develop

deb_package_deploy_master_tag:
  script: "~/ci-scripts/freenetis/freenetis/deb_package_deploy_master.sh"
  stage: deploy
  tags:
    - deb_repository
  only:
    - tags